@BASE_URL = https://this-rocking-api-dev.some-awesome-site.com
@TOKEN = {{ $dotenv JWT_EXAMPLE }}

###
GET {{BASE_URL}}/hello HTTP/1.1
Authorization: {{ TOKEN }}
Content-Type: application/json


### This shouldn't work because the token is missing
GET {{BASE_URL}}/hello HTTP/1.1


