##########################################################################################
@HOSTED_ZONE_NAME = {{ $dotenv HOSTED_ZONE_NAME }}

# *NOTE: Get this from `name` in the  ./package.json file
@APP_NAME =  api 

# *NOTE: Get this from `domain_suffix` in the  ./pipeline/terraform/env_configs file
@ENV = ""
##########################################################################################


# @BASE_URL = {{ APP_NAME }}{{ ENV }}.{{ HOSTED_ZONE_NAME }}
@BASE_URL = {{ APP_NAME }}.{{ HOSTED_ZONE_NAME }}
@TOKEN = {{ $dotenv JWT_EXAMPLE }}

##########################################################################################




###
GET {{BASE_URL}}/hello HTTP/1.1
Authorization: {{ TOKEN }}
Content-Type: application/json


### This shouldn't work because the token is missing
GET {{BASE_URL}}/hello HTTP/1.1
