@BASE_URL = https://this-rocking-api-dev.some-awesome-site.com
@TOKEN = {{ $dotenv JWT_EXAMPLE }}
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTc3OTI3NjcsImV4cCI6MTcxNzc5Mjc5N30.KtEINL8zja8yhl5OvGX9ktLo85DyOip5QhqKb9OZ3qE


###
GET {{BASE_URL}}/hello HTTP/1.1
Authorization: {{ TOKEN }}
Content-Type: application/json


### This shouldn't work because the token is missing
GET {{BASE_URL}}/hello HTTP/1.1


